using System;
using System.Dynamic;
using System.Linq;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;

namespace TrackMvvm.Views
{
    /// <summary>
    /// Interaction logic for HistoryDialog.xaml
    /// </summary>
    public partial class HistoryDialog : Window
    {
        public HistoryDialog()
        {
            InitializeComponent();
        }

        private void DataGrid_OnAutoGeneratedColumns(object sender, EventArgs e)
        {
            var dg = sender as DataGrid;
            var first = dg.ItemsSource.Cast<object>().FirstOrDefault() as DynamicObject;
            if (first == null) return;
            var names = first.GetDynamicMemberNames();
            foreach (var name in names)
            {
                dg.Columns.Add(new DataGridTextColumn { Header = name, Binding = new Binding(name) });
            }
        }
    }
}
